* #5: Added user guide.
exasol/virtual-schema-installer pull request #16
Opened 2021-07-20 10:10 UTC by AnastasiiaSergienko

Closes #5

2021-07-20 11:04 UTC, redcatbear requested changes
Reviewed with findings.

Using aliases makes the commands more readable and also scripts more portable. Also, in cross references always use anchors in Markdown please.

2021-07-20 11:04 UTC, redcatbear commented on doc/user_guide/user_guide.md
> +* The installer creates Exasol schema, adapter, connection and virtual schema names with quotation. It means the names you specify on the console are case-sensitive.
```suggestion
* The installer uses quotes when creating Exasol schema, adapter, connection and Virtual Schema name. That means the names you specify on the console are case-sensitive.
```

2021-07-21 10:34 UTC, AnastasiiaSergienko commented on doc/user_guide/user_guide.md
> +# Virtual Schema Installer User Guide
Done

2021-07-22 05:15 UTC, redcatbear commented on doc/user_guide/user_guide.md
> +# Virtual Schema Installer User Guide
Did you push this change? I don't see it.

2021-07-22 05:16 UTC, redcatbear requested changes
One change seems to be missing: introductory paragraph in user guide.

2021-07-22 09:33 UTC, redcatbear approved these changes

2021-07-22 09:38 UTC, merged